version: "3.8"

services:

  db:
    image: postgres:15
    
    container_name: "cars_db"
   
    restart: always
    
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testerpass
      POSTGRES_DB: carros
    
    ports:
      - "5432:5432"
    
    volumes:
      - carros_data:/var/lib/postgresql/data

volumes:
  carros_data:
